let token=localStorage.getItem("cf_token"),loginMode=true,questions=[],qi=0,answers=[],timer;
const $=id=>document.getElementById(id);
function api(path,opts={}){opts.headers=opts.headers||{};if(token)opts.headers.Authorization="Bearer "+token;return fetch(path,opts).then(async r=>{let d=await r.json().catch(()=>({detail:"Server error"}));if(!r.ok)throw new Error(d.detail||"Request failed");return d})}
function boot(){if(token){$("auth").classList.add("hidden");$("app").classList.remove("hidden");loadMe();page("dashboard")}else{$("auth").classList.remove("hidden");$("app").classList.add("hidden")}}
function toggleAuth(){loginMode=!loginMode;$("authTitle").textContent=loginMode?"Welcome back":"Create your account";$("nameWrap").classList.toggle("hidden",loginMode);$("authToggle").textContent=loginMode?"Create an account":"I already have an account";$("authMsg").textContent=""}
async function auth(){try{let body={email:$("email").value,password:$("password").value};if(!loginMode)body.name=$("name").value;let d=await api(loginMode?"/api/auth/login":"/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});token=d.token;localStorage.setItem("cf_token",token);boot()}catch(e){$("authMsg").textContent=e.message}}
async function loadMe(){try{let u=await api("/api/me");$("hello").textContent="Hi, "+u.name;$("roleDash").textContent=u.target_role}catch(e){logout()}}
function logout(){localStorage.removeItem("cf_token");token=null;location.reload()}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("hidden",x.id!==id));document.querySelectorAll("nav a").forEach(x=>x.classList.toggle("active",x.dataset.page===id));if(id==="jobs")loadJobs();if(id==="skills")loadSkills();if(id==="dashboard")loadDashboard();scrollTo(0,0)}
document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>page(a.dataset.page));
async function loadDashboard(){try{let [r,h]=await Promise.all([api("/api/resume/analyze",{method:"GET"}).catch(()=>null),api("/api/interviews")]);if(h[0]){$("intscore").textContent=h[0].score;$("latest").innerHTML=`<b>${h[0].role}</b><p>${h[0].score}/100 · ${new Date(h[0].date).toLocaleDateString()}</p>`}else $("latest").textContent="No interview yet. Start your first practice."}catch{}}
async function loadJobs(){let q=$("search").value;let data=await api("/api/jobs?q="+encodeURIComponent(q));$("jobsList").innerHTML=data.map(j=>`<div class="card job"><div class="logo">${j.company.slice(0,2).toUpperCase()}</div><div><h3>${j.title}</h3><p>${j.company} · ${j.location}</p><p>${j.description}</p><div class="tags">${j.skills.map(s=>`<span>${s}</span>`).join("")}</div></div><div class="match">${j.match}% match</div></div>`).join("")}
$("search").addEventListener("keydown",e=>{if(e.key==="Enter")loadJobs()});
$("resumeFile").addEventListener("change",e=>uploadResume(e.target.files[0]));
async function uploadResume(file){if(!file)return;let fd=new FormData();fd.append("file",file);try{let d=await api("/api/resume/analyze",{method:"POST",body:fd});$("resumeResult").classList.remove("hidden");$("resumeResult").innerHTML=`<div class="score">${d.ats_score}</div><p>ATS-style score for <b>${d.filename}</b></p><h3>Strengths</h3><p>✓ ${d.strengths.join("<br>✓ ")}</p><h3>Improve next</h3><p>⚠ ${d.improvements.join("<br>⚠ ")}</p>`;$("ats").textContent=d.ats_score;loadJobs();loadSkills()}catch(e){alert(e.message)}}
$("drop").onclick=e=>{if(e.target.tagName!=="BUTTON")$("resumeFile").click()};$("drop").ondragover=e=>e.preventDefault();$("drop").ondrop=e=>{e.preventDefault();uploadResume(e.dataTransfer.files[0])};
async function begin(){let role=$("iRole").value;let d=await api("/api/interview/questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role,difficulty:$("difficulty").value,type:$("itype").value})});questions=d.questions;qi=0;answers=[];$("setup").classList.add("hidden");$("room").classList.remove("hidden");showQ();runTimer()}
function showQ(){ $("qn").textContent=qi+1;$("question").textContent=questions[qi].question;$("answer").value="";$("eval").innerHTML=""}
function runTimer(){clearInterval(timer);let n=60;$("timer").textContent="01:00";timer=setInterval(()=>{n--;$("timer").textContent="00:"+String(n).padStart(2,"0");if(n<=0)submitAnswer()},1000)}
async function submitAnswer(){let a=$("answer").value.trim();if(!a){$("eval").innerHTML='<div class="feedback">Write an answer before submitting.</div>';return}clearInterval(timer);let d=await api("/api/interview/evaluate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role:$("iRole").value,question:questions[qi].question,answer:a})});answers.push({question:questions[qi].question,answer:a,...d});$("eval").innerHTML=`<div class="feedback"><b>${d.score}/100</b> · ${d.feedback}<br><br><b>Improve:</b> ${d.improvements.join(" · ")}</div>`;setTimeout(()=>qi<questions.length-1?(qi++,showQ(),runTimer()):finish(),900)}
function skipQ(){qi<questions.length-1?(qi++,showQ(),runTimer()):finish()}
async function finish(){clearInterval(timer);let score=Math.round(answers.reduce((a,b)=>a+b.score,0)/answers.length);await api("/api/interview/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role:$("iRole").value,score,answers,feedback:"Review your answer-level feedback before the next attempt."})});$("room").innerHTML=`<div class="score">${score}</div><h3>Interview complete 🎉</h3><p>Review the answer feedback and repeat the interview to improve your score.</p><button class="btn primary" onclick="location.reload()">Practice Again →</button>`;$("intscore").textContent=score}
async function loadSkills(){try{let role=$("iRole").value;let d=await api("/api/skill-gap?role="+encodeURIComponent(role));$("skillsBox").innerHTML=d.skills.map(s=>`<div class="skill"><span>${s.skill}</span><div class="bar"><i style="width:${s.score}%"></i></div><b>${s.score}%</b></div>`).join("")}catch{}}
boot();
